name: "PR: Request Remove preview"
on:
  pull_request:
    types:
      - closed
      - locked
    branches:
      - main
      - dev
jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        run: |
          echo -n ${{ github.event.number }} > ./NR
      - name: Store build result
        uses: actions/upload-artifact@v2
        with:
          name: pages
          path: ./NR
      - name: Do nothing
        run: echo "Trigger real remove process"
