name: "PR: Deploy preview"
on:
  workflow_run:
    workflows: ["PR: Build"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Download artifact"
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pages"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pages.zip', Buffer.from(download.data));
      - name: Unzip
        run: unzip -qq pages.zip -d build
      - name: Deploy
        run: |
          cd build
          pr_number=$(cat NR)
          remote_branch="pr-$pr_number"
          remote_uri="https://$PR_GITHUB_ACTOR:$SECRET_PR_GITHUB_TOKEN@github.com/$PR_GITHUB_REPOSITORY.git"
          git init
          git config --local user.name "$GIT_USER_NAME"
          git config --local user.email "$GIT_USER_EMAIL"
          git add -A
          git commit -m "PR $GITHUB_REPOSITORY#$pr_number"
          git push -f "$remote_uri" "HEAD:$remote_branch"
        env:
          GIT_USER_NAME: github-actions[bot]
          GIT_USER_EMAIL: <41898282+github-actions[bot]@users.noreply.github.com>
          PR_GITHUB_ACTOR: ${{ github.repository_owner }}
          PR_GITHUB_REPOSITORY: ${{ secrets.PR_REPO_NAME }}
          SECRET_PR_GITHUB_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}

      - name: Comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const prNumber = Number(fs.readFileSync('./NR'));
            const branch = `pr-${prNumber}`;
            const url = `${process.env.PR_DEPLOY_ORIGIN}/${branch}/`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Your PR build is now available at [${url}](${url})!`,
            });
        env:
          PR_DEPLOY_ORIGIN: ${{ secrets.PR_DEPLOY_ORIGIN }}
